import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Play } from "next/font/google";
import { FaceitDataProvider } from "./providers";

const play = Play({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${play.className} overflow-hidden`}>
        <FaceitDataProvider>
          <Navbar />
          {children}
        </FaceitDataProvider>
      </body>
    </html>
  );
}
